apiVersion: transformers.example.co/v1
kind: ValueAnnotator
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/function: |
      container:
        image: example.docker.com/my-functions/valueannotator:1.0.0   
        mounts:
        - type: bind
          src: /Users/candiedcode/Code/
          dst: /test/
value: 'testing-volume-mounts'
